server:
  port: 8080

spring:
  application:
    name: pokedex-api

  cache:
    type: caffeine
    cache-names: pokemonDetails
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m

info:
  app:
    name: "Pokedex API"
    description: "API to fetch paginated Pokémons with basic info"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: ["*"]  # Expose all actuator endpoints

  endpoint:
    health:
      show-details: always
    info:
      enabled: true

logging:
  level:
    root: INFO
    com.karen.pokedex: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html